### ISSUE TITLE
Add v2.3.0 release to releases.json

### ISSUE THREAD

**Issue by danzhik** [OctopusDeploy/cli#354]
## The bug

`OctopusDeploy/install-octopus-cli-action` can not be used with `version: 2.3.0` because it can not be found at https://raw.githubusercontent.com/OctopusDeploy/cli/main/releases.json (taken from `OctopusDeploy/install-octopus-cli-action` [ `octopus-cli.ts` ](https://github.com/OctopusDeploy/install-octopus-cli-action/blob/main/src/octopus-cli.ts)

## Command to reproduce

Invoke `OctopusDeploy/install-octopus-cli-action@v3` in GitHub Actions with `version: 2.3.0`

```
      - name: "Install Octopus CLI"
        uses: OctopusDeploy/install-octopus-cli-action@v3
        with:
          version: 2.3.0
```

## Outcome

```
Run OctopusDeploy/install-octopus-cli-action@v3
Error: Error: A version satisfying '2.3.0' could not be found.
Error: Error: Failed to resolve endpoint URL to download: undefined
```

## Versions

**cli**: 2.3.0

**Octopus Server**: n/a

## Links
https://github.com/OctopusDeploy/cli/pull/353
